"""Getting the work out of here and into the NLE.

The most-used feature of every review tool in this category is not the review
screen — it is the button that pushes the notes into the timeline the editor is
actually cutting in. Findings and comments that cannot reach Premiere or Resolve
become a second place to look, and a second place to look is a place people stop
looking.

Two formats, both plain text, neither needing a plugin:

**CMX3600 EDL** — the scene as a stringout, one event per shot. Every editing
application made in the last forty years reads this.

**Marker CSV** — every finding and every comment, as markers with timecodes, in
the column layout DaVinci Resolve imports and Premiere can be pointed at.

One honest limitation, stated where it is decided rather than in a README: the
frame rate is a parameter, not a measurement. Nothing in the archive records the
frame rate of the original — the proxies are normalised on the way in — so an
EDL generated at 24 for footage shot at 25 will be wrong by one frame per second
of offset. The caller passes what the production shot at, and the value is
written into the EDL header where an assistant will see it.
"""

from __future__ import annotations

import csv
import io
import logging

log = logging.getLogger(__name__)

# What most of the world shoots. Wrong for a PAL production, which is why it is
# a default and not a constant.
DEFAULT_FPS = 24.0


def timecode(seconds: float, fps: float = DEFAULT_FPS) -> str:
    """HH:MM:SS:FF, non-drop.

    Non-drop deliberately. Drop-frame is a 29.97 counting convention for
    broadcast running time; using it here would change what the numbers mean for
    the majority of callers to fix an arithmetic error the minority have, and
    the semicolon that signals it is the kind of thing that silently imports
    wrong.
    """
    if seconds < 0:
        seconds = 0.0
    total_frames = round(seconds * fps)
    frames = total_frames % round(fps)
    total_seconds = total_frames // round(fps)
    return (
        f"{total_seconds // 3600:02d}:"
        f"{(total_seconds % 3600) // 60:02d}:"
        f"{total_seconds % 60:02d}:"
        f"{frames:02d}"
    )


def edl(title: str, entries: list[dict], fps: float = DEFAULT_FPS) -> str:
    """A CMX3600 EDL of one scene's stringout.

    Source timecode starts at zero for each clip rather than at a real camera
    timecode, because the archive does not hold one — the proxies were made from
    files whose start timecode was not carried through ingest. An assistant
    relinking this will match on the file name in the comment line, which is
    what they would do anyway.

    Each event carries the reason as a comment. An EDL that arrives without the
    reasoning is a list of numbers; the whole argument of this system is that
    the reason travels with the decision, and it should not stop travelling at
    the export boundary.
    """
    lines = [
        f"TITLE: {_ascii(title)[:70]}",
        "FCM: NON-DROP FRAME",
        f"* GENERATED BY TRIMBIN AT {fps:g} FPS",
        ("* FRAME RATE IS DECLARED, NOT MEASURED. CHECK IT AGAINST THE CAMERA ORIGINALS."),
        "",
    ]

    record_s = 0.0
    for i, entry in enumerate(entries, start=1):
        start = float(entry.get("start_s", 0.0))
        end = float(entry.get("end_s", 0.0))
        length = max(0.0, end - start)
        if length <= 0:
            continue

        reel = _reel(entry)
        lines.append(
            f"{i:03d}  {reel}  V     C        "
            f"{timecode(start, fps)} {timecode(end, fps)} "
            f"{timecode(record_s, fps)} {timecode(record_s + length, fps)}"
        )
        lines.append(f"* FROM CLIP NAME: {_ascii(str(entry.get('clip_id', '')))}")

        slug = _ascii(str(entry.get("slug", "")))
        take = entry.get("take_no", 0)
        lines.append(f"* SHOT {slug} TAKE {take}")

        reason = _ascii(str(entry.get("reason", ""))).strip()
        if reason:
            # Wrapped, because an EDL line longer than about eighty characters
            # is where some readers stop reading and others stop parsing.
            for chunk in _wrap(reason, 68):
                lines.append(f"* {chunk}")

        if entry.get("differs_from_circle"):
            lines.append(f"* NOTE: DIRECTOR CIRCLED TAKE {entry.get('circled_take')}")
        if entry.get("needs_review"):
            lines.append("* NOTE: CLOSE CALL, NOT CONFIRMED BY AN EDITOR")

        lines.append("")
        record_s += length

    return "\n".join(lines) + "\n"


# The column names Resolve expects on import. Premiere reads a marker list of
# its own, but it will also take this via a CSV import, and one format that two
# applications accept beats two formats that each accept one.
MARKER_COLUMNS = [
    "Marker Name",
    "Description",
    "In",
    "Out",
    "Duration",
    "Marker Type",
    "Notes",
]

# Resolve's own colour vocabulary. Blue for something to know, yellow for
# something to look at, red for something that will stop delivery — the same
# three levels the findings carry, so an editor does not have to learn a second
# severity scale.
#
# The empty key is a real member. Rows written before severity was stored have
# none, and they get Cyan: visibly a marker, visibly not a claim about how bad
# it is. Folding them into Yellow would be inventing a level, which is the
# mistake this map replaced.
_COLOUR = {
    "blocking": "Red",
    "attention": "Yellow",
    "note": "Blue",
    "comment": "Green",
    "": "Cyan",
}


def markers(
    entries: list[dict],
    findings: list[dict],
    notes: list[dict],
    fps: float = DEFAULT_FPS,
) -> str:
    """Every finding and every comment, as timeline markers.

    Positioned in *record* time — where the moment lands in the assembled
    stringout — not in source time. A marker at 4.2 seconds into take 3 is
    useless on a timeline where take 3 starts at 01:12; converting here is the
    difference between markers that land on the frame and markers that land
    somewhere in the general area.
    """
    offsets: dict[str, list[tuple[float, float, float]]] = {}
    record_s = 0.0
    for entry in entries:
        start = float(entry.get("start_s", 0.0))
        end = float(entry.get("end_s", 0.0))
        length = max(0.0, end - start)
        if length <= 0:
            continue
        offsets.setdefault(str(entry.get("clip_id", "")), []).append((record_s, start, length))
        record_s += length

    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=MARKER_COLUMNS, lineterminator="\n")
    writer.writeheader()

    for finding in findings:
        placed = _place(finding, offsets, fps)
        if placed is None:
            continue
        in_tc, out_tc, duration_tc = placed
        severity = str(finding.get("severity") or "")
        writer.writerow(
            {
                "Marker Name": str(finding.get("code", "finding")),
                "Description": str(finding.get("detail", "")),
                "In": in_tc,
                "Out": out_tc,
                "Duration": duration_tc,
                "Marker Type": _COLOUR.get(severity, "Cyan"),
                # "severity not recorded" rather than a blank, so an editor reading
                # the column knows the difference between a level we left out and a
                # level we thought was low.
                "Notes": (
                    f"take {finding.get('take_no', '')} · {severity}"
                    if severity
                    else f"take {finding.get('take_no', '')} · severity not recorded"
                ),
            }
        )

    for note in notes:
        placed = _place(note, offsets, fps)
        if placed is None:
            continue
        in_tc, out_tc, duration_tc = placed
        writer.writerow(
            {
                "Marker Name": str(note.get("author", "note")),
                "Description": str(note.get("body", "")),
                "In": in_tc,
                "Out": out_tc,
                "Duration": duration_tc,
                "Marker Type": _COLOUR["comment"],
                "Notes": "comment",
            }
        )

    return buffer.getvalue()


def _place(
    item: dict, offsets: dict[str, list[tuple[float, float, float]]], fps: float
) -> tuple[str, str, str] | None:
    """Move a source-time span onto the assembled timeline.

    Returns None when the marker belongs to a take that is not in the stringout
    — a rejected take's findings are real and worth keeping, and putting them on
    a timeline that does not contain that take would place them on whatever
    happens to be there instead, which is worse than omitting them.
    """
    clip_id = str(item.get("clip_id", ""))
    if clip_id not in offsets:
        return None

    at_s = float(item.get("start_s", item.get("at_s", 0.0)) or 0.0)
    to_s = float(item.get("end_s", item.get("to_s", 0.0)) or 0.0)

    # The same take may contribute several ranges. Put the marker on the first
    # selected range that actually contains it, rather than overwriting the
    # earlier offset with the last occurrence of the clip.
    candidates = offsets[clip_id]
    record_start, source_start, length = next(
        (
            candidate
            for candidate in candidates
            if candidate[1] <= at_s <= candidate[1] + candidate[2]
        ),
        candidates[0],
    )

    # Clamp into the part of the take that was actually used. A finding at 0:52
    # of a take trimmed at 0:30 did happen, and the honest place for it on this
    # timeline is the last frame that survived rather than a frame that did not.
    rel_start = min(max(at_s - source_start, 0.0), length)
    rel_end = min(max(to_s - source_start, rel_start), length)

    return (
        timecode(record_start + rel_start, fps),
        timecode(record_start + rel_end, fps),
        timecode(max(rel_end - rel_start, 1.0 / fps), fps),
    )


def _reel(entry: dict) -> str:
    """An eight-character reel name, which is all CMX3600 has room for.

    Built from the shot and take rather than truncating a uuid, because a reel
    column of sliced hexadecimal helps nobody standing at a machine. S12AT03 is
    readable across a room.
    """
    slug = "".join(c for c in str(entry.get("slug", "")) if c.isalnum()).upper()
    take = int(entry.get("take_no", 0) or 0)
    reel = f"S{slug}T{take:02d}"[:8]
    return reel.ljust(8)


def _ascii(text: str) -> str:
    """EDLs are an ASCII format and some readers still mean it literally.

    A curly quote in a reason is not worth an import failure, so the characters
    that appear in our own prose are replaced rather than stripped — an em dash
    becoming a hyphen keeps the sentence, and becoming nothing does not.
    """
    swaps = {
        "—": "-",
        "–": "-",
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "…": "...",
        "·": "-",
    }
    for bad, good in swaps.items():
        text = text.replace(bad, good)
    return text.encode("ascii", "ignore").decode("ascii")


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            if current:
                lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines
