"""Getting the work out of here and into the NLE.

The most-used feature of every review tool in this category is not the review
screen — it is the button that pushes the notes into the timeline the editor is
actually cutting in. Findings and comments that cannot reach Premiere or Resolve
become a second place to look, and a second place to look is a place people stop
looking.

Two formats, both plain text, neither needing a plugin:

**CMX3600 EDL** — the scene as a stringout, one event per shot. Every editing
application made in the last forty years reads this.

**Marker CSV** — every finding and every comment, as markers with timecodes, in
the column layout DaVinci Resolve imports and Premiere can be pointed at.

The scene API supplies the measured source rate when sources agree, or an
explicit export rate for mixed media. Camera-start timecode is not archived:
source timecodes remain zero-based and must be checked when relinking originals.
"""

from __future__ import annotations

import csv
import io
import logging

log = logging.getLogger(__name__)

# What most of the world shoots. Wrong for a PAL production, which is why it is
# a default and not a constant.
DEFAULT_FPS = 24.0


def timecode(seconds: float, fps: float = DEFAULT_FPS) -> str:
    """HH:MM:SS:FF, non-drop.

    Non-drop deliberately. Drop-frame is a 29.97 counting convention for
    broadcast running time; using it here would change what the numbers mean for
    the majority of callers to fix an arithmetic error the minority have, and
    the semicolon that signals it is the kind of thing that silently imports
    wrong.
    """
    if seconds < 0:
        seconds = 0.0
    total_frames = round(seconds * fps)
    return _frame_timecode(total_frames, fps)


def _frame_timecode(total_frames: int, fps: float) -> str:
    frames = total_frames % round(fps)
    total_seconds = total_frames // round(fps)
    return (
        f"{total_seconds // 3600:02d}:"
        f"{(total_seconds % 3600) // 60:02d}:"
        f"{total_seconds % 60:02d}:"
        f"{frames:02d}"
    )


def edl(title: str, entries: list[dict], fps: float = DEFAULT_FPS) -> str:
    """A CMX3600 EDL of one scene's stringout.

    Source timecode starts at zero for each clip rather than at a real camera
    timecode, because the archive does not hold one — the proxies were made from
    files whose start timecode was not carried through ingest. An assistant
    relinking this will match on the file name in the comment line, which is
    what they would do anyway.

    Each event carries the reason as a comment. An EDL that arrives without the
    reasoning is a list of numbers; the whole argument of this system is that
    the reason travels with the decision, and it should not stop travelling at
    the export boundary.
    """
    measured_rates = sorted(
        {
            round(float(item.get("fps", 0) or 0), 3)
            for item in entries
            if float(item.get("fps", 0) or 0) > 0
        }
    )
    frame_note = (
        f"* SOURCE FRAME RATE MEASURED AT {measured_rates[0]:g} FPS."
        if len(measured_rates) == 1
        else (
            "* MIXED MEASURED SOURCE FRAME RATES: "
            f"{', '.join(f'{rate:g}' for rate in measured_rates)} FPS; EXPORT IS {fps:g} FPS."
        )
        if measured_rates
        else "* SOURCE FRAME RATE UNMEASURED; VERIFY AGAINST CAMERA ORIGINALS."
    )
    lines = [
        f"TITLE: {_ascii(title)[:70]}",
        "FCM: NON-DROP FRAME",
        f"* GENERATED BY TRIMBIN AT {fps:g} FPS",
        frame_note,
        "* SOURCE TC IS ZERO-BASED; VERIFY CAMERA TIMECODE WHEN RELINKING ORIGINALS.",
        "",
    ]

    record_frames = 0
    for i, entry in enumerate(entries, start=1):
        start = float(entry.get("start_s", 0.0))
        end = float(entry.get("end_s", 0.0))
        start_frame, end_frame = round(max(0.0, start) * fps), round(max(0.0, end) * fps)
        length_frames = end_frame - start_frame
        if length_frames <= 0:
            continue

        reel = _reel(entry)
        lines.append(
            f"{i:03d}  {reel}  V     C        "
            f"{_frame_timecode(start_frame, fps)} {_frame_timecode(end_frame, fps)} "
            f"{_frame_timecode(record_frames, fps)} "
            f"{_frame_timecode(record_frames + length_frames, fps)}"
        )
        source_name = str(entry.get("source_filename") or entry.get("clip_id", ""))
        lines.append(f"* FROM CLIP NAME: {_ascii(source_name)}")
        if not entry.get("source_filename"):
            lines.append("* WARNING: ORIGINAL FILENAME MISSING; VERIFY SOURCE RELINK.")
        if "proxy_uri" in entry and not entry["proxy_uri"]:
            lines.append("* WARNING: PREVIEW MEDIA MISSING; VERIFY SOURCE AVAILABILITY.")

        slug = _ascii(str(entry.get("slug", "")))
        take = entry.get("take_no", 0)
        lines.append(f"* SHOT {slug} TAKE {take}")

        reason = _ascii(str(entry.get("reason", ""))).strip()
        if reason:
            # Wrapped, because an EDL line longer than about eighty characters
            # is where some readers stop reading and others stop parsing.
            for chunk in _wrap(reason, 68):
                lines.append(f"* {chunk}")

        if entry.get("differs_from_circle"):
            lines.append(f"* NOTE: DIRECTOR CIRCLED TAKE {entry.get('circled_take')}")
        if entry.get("needs_review"):
            lines.append("* NOTE: CLOSE CALL, NOT CONFIRMED BY AN EDITOR")

        lines.append("")
        record_frames += length_frames

    return "\n".join(lines) + "\n"


# The column names Resolve expects on import. Premiere reads a marker list of
# its own, but it will also take this via a CSV import, and one format that two
# applications accept beats two formats that each accept one.
MARKER_COLUMNS = [
    "Marker Name",
    "Description",
    "In",
    "Out",
    "Duration",
    "Marker Type",
    "Notes",
]

# Resolve's own colour vocabulary. Blue for something to know, yellow for
# something to look at, red for something that will stop delivery — the same
# three levels the findings carry, so an editor does not have to learn a second
# severity scale.
#
# The empty key is a real member. Rows written before severity was stored have
# none, and they get Cyan: visibly a marker, visibly not a claim about how bad
# it is. Folding them into Yellow would be inventing a level, which is the
# mistake this map replaced.
_COLOUR = {
    "blocking": "Red",
    "attention": "Yellow",
    "note": "Blue",
    "comment": "Green",
    "": "Cyan",
}


def markers(
    entries: list[dict],
    findings: list[dict],
    notes: list[dict],
    fps: float = DEFAULT_FPS,
) -> str:
    """Every finding and every comment, as timeline markers.

    Positioned in *record* time — where the moment lands in the assembled
    stringout — not in source time. A marker at 4.2 seconds into take 3 is
    useless on a timeline where take 3 starts at 01:12; converting here is the
    difference between markers that land on the frame and markers that land
    somewhere in the general area.
    """
    offsets: dict[str, list[tuple[float, float, float]]] = {}
    record_s = 0.0
    for entry in entries:
        start = round(max(0.0, float(entry.get("start_s", 0.0))) * fps) / fps
        end = round(max(0.0, float(entry.get("end_s", 0.0))) * fps) / fps
        length = max(0.0, end - start)
        if length <= 0:
            continue
        offsets.setdefault(str(entry.get("clip_id", "")), []).append((record_s, start, length))
        record_s += length

    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=MARKER_COLUMNS, lineterminator="\n")
    writer.writeheader()

    for finding, placed in (
        (item, position) for item in findings for position in _places(item, offsets, fps)
    ):
        in_tc, out_tc, duration_tc = placed
        severity = str(finding.get("severity") or "")
        writer.writerow(
            {
                "Marker Name": str(finding.get("code", "finding")),
                "Description": str(finding.get("detail", "")),
                "In": in_tc,
                "Out": out_tc,
                "Duration": duration_tc,
                "Marker Type": _COLOUR.get(severity, "Cyan"),
                # "severity not recorded" rather than a blank, so an editor reading
                # the column knows the difference between a level we left out and a
                # level we thought was low.
                "Notes": (
                    f"take {finding.get('take_no', '')} · {severity}"
                    if severity
                    else f"take {finding.get('take_no', '')} · severity not recorded"
                ),
            }
        )

    for note, placed in (
        (item, position) for item in notes for position in _places(item, offsets, fps)
    ):
        in_tc, out_tc, duration_tc = placed
        writer.writerow(
            {
                "Marker Name": str(note.get("author", "note")),
                "Description": str(note.get("body", "")),
                "In": in_tc,
                "Out": out_tc,
                "Duration": duration_tc,
                "Marker Type": _COLOUR["comment"],
                "Notes": "comment",
            }
        )

    return buffer.getvalue()


def _places(
    item: dict, offsets: dict[str, list[tuple[float, float, float]]], fps: float
) -> list[tuple[str, str, str]]:
    """Place only intersections with used source media, including reused ranges.

    An excluded issue stays in the archive; pinning it to a surviving clean
    frame would incorrectly mark that clean frame as defective.
    """
    clip_id = str(item.get("clip_id", ""))
    if clip_id not in offsets:
        return []

    at_s = float(item.get("start_s", item.get("at_s", 0.0)) or 0.0)
    to_s = float(item.get("end_s", item.get("to_s", 0.0)) or 0.0)

    placed = []
    for record_start, source_start, length in offsets[clip_id]:
        source_end = source_start + length
        if to_s <= at_s:  # Point comments belong to one half-open interval.
            if not source_start <= at_s < source_end:
                continue
            start, end = at_s, min(source_end, at_s + 1.0 / fps)
        else:
            start, end = max(at_s, source_start), min(to_s, source_end)
            if end <= start:
                continue
        placed.append(
            (
                timecode(record_start + start - source_start, fps),
                timecode(record_start + end - source_start, fps),
                timecode(max(end - start, 1.0 / fps), fps),
            )
        )
    return placed


def _reel(entry: dict) -> str:
    """An eight-character reel name, which is all CMX3600 has room for.

    Built from the shot and take rather than truncating a uuid, because a reel
    column of sliced hexadecimal helps nobody standing at a machine. S12AT03 is
    readable across a room.
    """
    slug = "".join(c for c in str(entry.get("slug", "")) if c.isalnum()).upper()
    take = int(entry.get("take_no", 0) or 0)
    reel = f"S{slug}T{take:02d}"[:8]
    return reel.ljust(8)


def _ascii(text: str) -> str:
    """EDLs are an ASCII format and some readers still mean it literally.

    A curly quote in a reason is not worth an import failure, so the characters
    that appear in our own prose are replaced rather than stripped — an em dash
    becoming a hyphen keeps the sentence, and becoming nothing does not.
    """
    swaps = {
        "—": "-",
        "–": "-",
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "…": "...",
        "·": "-",
    }
    for bad, good in swaps.items():
        text = text.replace(bad, good)
    return text.encode("ascii", "ignore").decode("ascii")


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            if current:
                lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines
